### PR TITLE
Update Router.php

### PR DESCRIPTION
**Pull request by lai0n**
- Removal excessive white spaces
- Created a new function that tests class calls

### CODE REVIEW

**Comment by sant0ro** [comment]
I didn't unserstood what your PR changes, only blank lines (that are good) and a new class.

PHPUnit doesn't work in that way. You need explicitely add a routineTest for the new Feature "class@method".

Thanks!

**Comment by lai0n** [comment]
@sant0ro Look the line 538

**Comment by sant0ro** [comment]
Right.

**Comment by bramus** [comment]
Merged in 7fcdede, in which I reverted the line endings style back to Unix style instead of Windows style.

**Pull request closed without merging**
