### PR TITLE
Multiple Changes on the Router Core

### PR DESCRIPTION
**Pull request by sant0ro**
This **Pull Requests** adds more checks, performance gains and new features on the `bramus/router` package.

**New Features**
* Capability of Curly Braces as Pattern, like `/home/{something}/and/{else}', actually they're converted unto `\w+`
* Capability of set a Default Namespace for Lookup on Callables `Class@Method`

**Checks**
* Sometimes getallheaders() is present but went unto problems and return false, now this is checked.
* Now storing headers and method unto a property from `Router` and only first time usage updates it. (<small>Observation.: For getRequestMethod added check if `REQUEST_METHOD` change, since phpunit overwrites it many times</small>)
* Other more checks.

Each feature/change it's in a separate commit.
Also created unit tests for each change.

If the Pull Request gots approved, I will update the README.md with the new features.

### CODE REVIEW

**Comment by sant0ro** [comment]
It seems that phpunit is hanging on php 7.0, updating phpunit version from the package.

**Comment by sant0ro** [comment]
It seems that ever with `phpunit` on `5.0` version isn't compatible. Downgrading unto `4.8` version.

**Comment by sant0ro** [comment]
Observation.: #35 updated the phpunit version. Something that isn't good, since your purpose is compatibility with php 5.3

As you can see his builds were broken. That's the reason that I downgraded the phpunit version.

No needing of using 5.5.* or 5.0.*

**Comment by sant0ro** [comment]
@bramus waiting your answer.

**Comment by bramus** [comment]
Hi @sant0ro, 

Looking good, thanks for these additions! :-)

I'd change two things though:

1. I'd omit [the second clause in `getRequestMethod()`](https://github.com/bramus/router/pull/38/commits/9b60e5395a6dc723091325b41716c82bb9eb1f99#diff-517e313cd01b02b05954b5410d376513R238), and adjust the tests instead. That way the tests will mimic a real life scenario (e.g. work with a new instance of the router on each request), and the logic contained in the `getRequestMethod()` function will be used _(here `$headers['X-HTTP-Method-Override']` for example isn't used, whilst `getRequestMethod()` does take it into account)_.

2. I'd adjust [these two `class_exists()` calls](https://github.com/bramus/router/pull/38/commits/e17f1b6ec6ed7f18ac4827f837077285f207c379#diff-517e313cd01b02b05954b5410d376513R388), so that `class_exists()` is called only once, by overwriting `$controller` right before the `if` statement _(or even a little higher up the code)_

```
if ($this->getNamespace() !== '') {
  $controller = $this->getNamespace() . '\\' . $controller;
}
```

Regards,
B!

**Comment by sant0ro** [comment]
Hi @bramus I will adjust those things. You can also comment those reviews, directly on the code, by the new GitHub reviewing system.

Cheers!

**Comment by sant0ro** [comment]
@bramus Updated doing the following things.:

1. I did all the changes that you asked to do. I'm not 100% sure if what I did on the `class_exists` was what you want.
2. For practical use, changed the methods `getRequestMethod` and `getRequestHeaders` just to `headers()` and `method`, since it's a convention that an Router would treat Requesting data. Also those are public functions and since all usable public function are quite simple with naming, why not doing with those too.
3. Changed header("Not Found") to just http_response_code(404), avoiding the headers already sent.
4. Removed xdebug function call that may cause problems if your php environment hasn't xdebug enable, and that function only works with active xdebug session, without it, just return nothing like you said on your `@todo`.
4. Removed the property `requestedMethod` since I already created one called `method`, so renamed your calls to it.

**Comment by sant0ro** [comment]
It seems that what I do on the ternary comparator doesn't work either on php 5.4 and 5.3, changing it to another approach.

**Comment by sant0ro** [comment]
@bramus finally fixed it.

1. Rolled back to `header()` since php 5.3 doesn't have `http_response_code()`
2. Fixed the risky status of the `all()` test (phpunit).
3. Improved some little things.
4. Put the setting of the namespace, directly on the on `run()` method, after the callback.
5. Finally I think got a correct `class_exists()`.

**Comment by sant0ro** [comment]
@bramus ?

**Comment by sant0ro** [comment]
@bramus are you here?

**Comment by bramus** [comment]
Hi @sant0ro,

Thanks for the changes, but I must say you've done a bit too much on the internal side with those last few commits, making this pull request a rather big one containing lots and lots of changes.

I'll try cherry picking the essential ones (with a focus on the ones before Jun 6), as the features introduced are a very welcome addition :-)

Regards,
Bramus.

**Comment by sant0ro** [comment]
Thanks, @bramus 

Pick what you want :)

**Comment by sant0ro** [comment]
I need to agree that this is a really big pull request...

**Comment by bramus** [comment]
Pinging @sant0ro: finally got round to merging this one. Feel free to test. If found OK I'll tag it as 1.2 :-)

**Comment by sant0ro** [comment]
Nice @bramus When I tested everything was Okay.

**Pull request closed without merging**
