### PR TITLE
CORS Edit

### PR DESCRIPTION
**Pull request by tomgs**
This is not strictly relevant, but would be awesome to see when Googling for this problem.
I would keep it here for visibility, but up to you.
Thanks for this cool router!

### CODE REVIEW

**Comment by bramus** [comment]
This looks like wrong information to me. What you need to do is send over `Access-Control-Allow-Origin: *` _(amongst others)_ with [the preflight `OPTIONS` request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) that gets sent before the actual `GET` or `POST` request.

**Comment by tomgs** [comment]
I actually had:
```
$router->options('/.*', function() {
	header('Access-Control-Allow-Origin: *');
});
```

And still caught that issue. I think some mention of CORS would go a long way, either way.

**Comment by ovflowd** [comment]
@tomgs did you checked if the header is being sent at all?

Also this header is not enough in order to make CORS work. @bramus is right. There are a couple of headers you should add.

Give a read to https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

Working example should be:

```{php}
$router->options('/.*', function() {
	header('Access-Control-Allow-Origin: *');
	header('Access-Control-Allow-Methods: POST, GET, OPTIONS');
	header('Access-Control-Allow-Headers: Content-Type');
	// Optional
	header('Access-Control-Max-Age: 86400');
});
```

While saying this works, I would not recommend this at all. I would prefer creating groups and then options per route / group.

Remember, you're saying with `*` that anyone can request content on the `POST and GET` methods.

It's truly recommended to configure this field depending to what you need 😄

**Comment by tomgs** [comment]
@ovflowd of course I checked, that was not the point of this PR - i just gave an example of a test I created.

My logic is as follows - if someone is using `bramus/router`, and is hitting a CORS problem, I'd suspect having an entry on CORS on the README is not such a bad thing. It is the single source of truth for the project, and I'd like to use it when troubleshooting.

**Comment by ovflowd** [comment]
Oh. Yes, I agree with you. But your changes on the `README.md` doesn't explain how to actually solve the problem 😅 

Would be nice referring MDN and adding a snippet with examples 😄

**Comment by tomgs** [comment]
I get the feeling the author doesn't really want to add anything CORS-related, or am I wrong?
If that makes sense, I'll write up something later today that's a bit more generic and actually reference using CORS with `bramus/router`.

**Comment by ovflowd** [comment]
If you read his answer, he's not against adding CORS related information. He just said that your information doesn't sum up. And I agree 😄 

You don't need to reference `axios` / `fetch` or anything like that. Also your information also wasn't related to `bramus/router` at all. It was just saying hey if you see this error is a CORS error.

It would be more interesting adding informations regarding how to properly handle a pre-flight request with `bramus/route` 😃

**Comment by tomgs** [comment]
So, conclusion: Add some information about CORS to the README, do not be overly-specific with exactly the error message I received (since it is not relevant to the library, per se) and be a happy camper.

Dope! :)

**Comment by bramus** [comment]
Correct :)

**Comment by ovflowd** [comment]
@tomgs feel free to create a new PR, since this one is already closed.

Happy hacking <3

**Comment by ovflowd** [comment]
@bramus I believe this PR could be reopened, so the author could properly work on the documentation updates 😄

**Comment by tomgs** [comment]
Ah, I actually killed the fork I think. I need to remember to iterate back to things... will (I hope, if I don't get distracted for another half year) write this up this week sometime.

**Pull request closed without merging**
