### PR TITLE
Resolves Issue#32

### PR DESCRIPTION
**Pull request by dylanharty**
Changed function handle(…) access modifier from private to protected
for child override.

### CODE REVIEW

**Comment by sant0ro** [comment]
Why exactly you need that this function becomes `protected`
To create a class that extends the Routing Module?

**Comment by bramus** [comment]
Asking the same question as @sant0ro. It's essentially the core function of the router; Overriding it may render it broken. What scenario/situation requires the `protected` access modifier?

**Comment by dylanharty** [comment]
To have the ability to override from an extended class. Such as in my case adding named routing and still having the ability to use composer with the official repo. Instead of forking and doing it. It is more about the possibility of using the child context without locking the context to the parent. It will not affect performance but gives the possibility to use child overriding. This is the easiest way without refactoring the params matching within the handle core functionality. Does that answer your concerns?

**Comment by bramus** [comment]
@dylanharty Still not to keen on changing `handle()` to `protected` though, as the change can do more harm than good. I'd rather see named routing get built into this project as a feature (perhaps for version 2?) than implementing this quick-n-dirty shortcut.

**Comment by dylanharty** [comment]
@bramus I don't see the harm, as outlined here [public vs private vs protected PHP](http://stackoverflow.com/questions/4361553/what-is-the-difference-between-public-private-and-protected). Quick yes, but not dirty. It allows adventurous people to extend the routers main components. Key word allows. This way it **can** be overridden and still act like a private function + allowing extended class's context. What are you thinking on your verdict?

**Comment by sant0ro** [comment]
@dylanharty Why you not propose a pull request that can create an additional functionality to the Router? Like a Mutator. (I'm porting the concept of Laravel Mutators).

Since this Router isn't only being used by you... It's a real doubt by changing this word `private` to `protected`.

You see, the `handle()` it's like the heart of the Router.

**Comment by dylanharty** [comment]
I understand that this is not just used by me. It passed the initial tests(PHPUnit/Travis) and does not seem to break anything. I also have it working flawlessly on a server, in the child and tested for anomalies in the parent. Seems like the decision is made. Also if i add functionality(technically this change does too), it will be in the handle(). If you guys want we can take this chat "offline" over email about adding in name routing(modified routes), or we can keep the discussion rolling here.

**Comment by bramus** [comment]
Closing this one. See https://github.com/bramus/router/issues/32

**Pull request closed without merging**
