### PR TITLE
Update Router.php

### PR DESCRIPTION
**Pull request by sant0ro**
Edit of @lai0n version of his pull request. But with some changes.

### CODE REVIEW

**Comment by sant0ro** [comment]
Fixes from @lai0n pull requesy (#21)

1. First removed useless checks of method_exists
2. Removed the throw exception, that cause abort of the execution of the script, a router need ignore the invalid data. 
3. Created option of invoking static members and non-static members
4. Removed some useless blank lines and extra lines (cleaned a little the code)
5. Improved way of call the members, and typed a little documentation in my code.

**Comment by tleb** [comment]
I'm not sure removing most of the blank lines really helps. Whitespaces create blocks in your code.

**Comment by sant0ro** [comment]
@tleb not only blank spaces are the changes of this PR.

Also i will provide a second version of this PR.

**Comment by sant0ro** [comment]
@bramus will this PR be accepted?

**Comment by bramus** [comment]
@sant0ro: In it's current form this PR won't be merged. 

Here's why:

- Commits aren't singular: commit `fc52d5156a7c370e16cccd6ea9ea37b707e41108` for example affects whitespace, and includes new functionality. This should be two separate commits.
- The commits contain big changes, outside of scope of the core functionality added: in commit `d5e3280643d8632576b2bfc2a825f2455cf8b050` for example the `Router` class has become `final`. This is a change with big impact, far outside of the core scope of this PR.
- The commits in this PR undo each other, loitering the timeline: in commit `d5e3280643d8632576b2bfc2a825f2455cf8b050` for example a lot of variables are renamed, and the in commit `b8488d90359c548faedf94e18e722ae503cfafe9` this is undone.
- The commits contain unnecessary changes: why do all comments now start with a non-capitalized word?
- The added functionality is incomplete: with the new functionality, an `@todo` is included in that snippet
- The added functionality is untested (see `tests/` subfolder)

Regards,
Bramus.

**Comment by sant0ro** [comment]
Okay! @bramus i will create a new Pull Request with all these things corrected.

**Pull request closed without merging**
